### ISSUE TITLE
[Solana] Exception caught while running hook cfn-auto-reloader-hook

### ISSUE THREAD

**Issue by Amet13** [aws-samples/aws-blockchain-node-runners#157]
## Description

I'm having suspicious logs for `cfn-auto-reloader-hook` after Solana's `heavy-rpc` config installation, see the error from logs below.

Might be some incorrect AWS Region passed with redundant double quotes:

```
cfnbootstrap.util.RemoteError: [Errno None] HTTPSConnectionPool(host='cloudformation.%22eu-central-1%22.amazonaws.com', port=443)
```
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: latest
- AWS CDK version: latest

## Reproduction Code [Required]

```bash
# tail -f /var/log/cfn-hup.log
2024-12-20 18:05:08,683 [ERROR] Exception caught while running hook cfn-auto-reloader-hook
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/update_hooks.py", line 625, in process
    self._process_hook(hook, metadata)
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/update_hooks.py", line 634, in _process_hook
    new_data = self._retrieve_path_data(hook.path)
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/update_hooks.py", line 721, in _retrieve_path_data
    self._resource_cache[logical_id] = self.client.describe_stack_resource(
  File "/usr/local/lib/python3.8/dist-packages/cfnbootstrap/util.py", line 233, in _retry
    raise last_error
cfnbootstrap.util.RemoteError: [Errno None] HTTPSConnectionPool(host='cloudformation.%22eu-central-1%22.amazonaws.com', port=443): Max retries exceeded with url: /?Action=DescribeStackResource&LogicalResourceId=WebServerHost&ContentType=JSON&StackName=%22arn%3Aaws%3Acloudformation%3Aeu-central-1%3A481665101473%3Astack%2Fsolana-single-node-extendedrpc%2Ff4a6d060-bef6-11ef-9303-0651f43e717d%22&Version=2010-05-15 (Caused by NewConnectionError('<cfnbootstrap.packages.requests.packages.urllib3.connection.HTTPSConnection object at 0x7f9d13d8efd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

```bash
# cat /etc/cfn/hooks.d/cfn-auto-reloader.conf 
[cfn-auto-reloader-hook]
triggers=post.update
path=Resources.WebServerHost.Metadata.AWS::CloudFormation::Init
action=/opt/aws/bin/cfn-init -v --stack "solana-single-node-extendedrpc" --resource WebServerHost --region "eu-central-1"

# cat /etc/cfn/cfn-hup.conf 
[main]
stack="arn:aws:cloudformation:eu-central-1:redacted:stack/solana-single-node-extendedrpc/redacted"
region="eu-central-1"
# The interval used to check for changes to the resource metadata in minutes. Default is 15
interval=2
```

- Install fresh version of Solana (from `heavy-rpc` template)
- Login to the node and check logs for cfn-hup

## Expected behavior

To not to see errors in cfn-auto-reloader-hook

## Actual behavior

Some errors in cfn-auto-reloader-hook

**Comment by frbrkoala** [comment]
Thanks for reporting this! There is a new update for Solana blueprint with support or ARM/Graviton architecture instances and refactored bash code in all the setup scripts. I checked the `/var/log/cfn-hup.log` log on the new node and it didn't show any errors. Let me know if the update had fixed this.
