### ISSUE TITLE
Solana RPC node returns connection refused

### ISSUE THREAD

**Issue by ko0hi** [aws-samples/aws-blockchain-node-runners#31]
- [ - ] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

Hi. I'm trying to run the single node setup.

After deploying it and doing ssh to the ec2 instance where the node is running, I got the following error with a health check request.

```
# error
curl: (7) Failed to connect to localhost port 8899: Connection refused
```

```bash
# request
curl http://localhost:8899 -X POST -H "Content-Type: application/json" -d ' {"jsonrpc":"2.0","id":1,"method":"getBlockHeight"}'
```

What am I missing?

#### Additional context
- I waited more than 2 hours. Does it take more?
- Validator's log showed only one line `Started Solana Validator.`

**Comment by ko0hi** [comment]
I was able to get a response with one of the following connected URLs.

![image](https://github.com/aws-samples/aws-blockchain-node-runners/assets/105577066/11acf7d1-913b-416b-967e-98cbcacc11c6)

I think this issue is just due to the lack of my knowledge about solana node. Let me close it. Thank you.

**Comment by ko0hi** [comment]
I found the solana node got stuck with the following error.

![image](https://github.com/aws-samples/aws-blockchain-node-runners/assets/105577066/bb07f221-784a-437f-ab99-e2ab6210158e)

`admin.rpc` exists in `/var/solana/data/ledger`.

![image](https://github.com/aws-samples/aws-blockchain-node-runners/assets/105577066/12c10de0-53d6-4c50-a6df-6efd701c923c).


This issue might be related?

https://github.com/solana-labs/example-helloworld/issues/294

**Comment by ko0hi** [comment]
I was able to manually run `solana-validator` with the following steps:

- Creating a symbolic link of `/var/solana/data/ledger`  in `/home/solana`
- Run `/home/solana/bin/validator.sh` at `/home/solana`

I guess the default path to `admin.rpc` is set to `./ledger/admin.rpc`.

I've been looking for the option of `solana-validator` to configure this path, but not found yet.

**Comment by ko0hi** [comment]
Still not succeeded.
I got the following error when the download of snapshot almost finishes (7m left).

```
thread 'main' panicked at 'Failed to open ledger database: UnableToSetOpenFileDescriptorLimit', core/src/validator.rs:1606:10
stack backtrace:
   0:     0x55797572f85a - std::backtrace_rs::backtrace::libunwind::trace::ha9053a9a07ca49cb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55797572f85a - std::backtrace_rs::backtrace::trace_unsynchronized::h9c2852a457ad564e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55797572f85a - std::sys_common::backtrace::_print_fmt::h457936fbfaa0070f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55797572f85a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5779d7bf7f70cb0c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x557975758e1e - core::fmt::write::h5a4baaff1bcd3eb5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:     0x55797572a275 - std::io::Write::write_fmt::h4bc1f301cb9e9cce
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:     0x55797572f625 - std::sys_common::backtrace::_print::h5fcdc36060f177e8
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55797572f625 - std::sys_common::backtrace::print::h54ca9458b876c8bf
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x557975730faf - std::panicking::default_hook::{{closure}}::hbe471161c7664ed6
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:     0x557975730ceb - std::panicking::default_hook::ha3500da57aa4ac4f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:     0x5579750e6a1e - solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}::h2b78401441241e56
  11:     0x5579757316dd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6507bddc3eebb4a5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:2001:9
  12:     0x5579757316dd - std::panicking::rust_panic_with_hook::h50c09d000dc561d2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:696:13
  13:     0x557975731459 - std::panicking::begin_panic_handler::{{closure}}::h9e2b2176e00e0d9c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
  14:     0x55797572fcc6 - std::sys_common::backtrace::__rust_end_short_backtrace::h5739b8e512c09d02
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  15:     0x557975731162 - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  16:     0x557973723863 - core::panicking::panic_fmt::hf33a1475b4dc5c3e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  17:     0x557973723d13 - core::result::unwrap_failed::hdff5465d74574b44
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
  18:     0x557973a7994c - solana_core::validator::Validator::new::h8b64386b933d4c44
  19:     0x557973860d3b - solana_validator::main::h8e9274a422e67f4f
  20:     0x5579738012c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbb010e5a4c1e74a0
  21:     0x5579737caea9 - std::rt::lang_start::{{closure}}::hf9686ac14756b0a6
  22:     0x5579757238dc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd6efcd3bec896f2c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
  23:     0x5579757238dc - std::panicking::try::do_call::hce04e543bb1f4cbb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  24:     0x5579757238dc - std::panicking::try::h3342dd4e1f680968
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  25:     0x5579757238dc - std::panic::catch_unwind::h148ce1e59ac0cee7
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  26:     0x5579757238dc - std::rt::lang_start_internal::{{closure}}::h25f9dda2057a67fe
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
  27:     0x5579757238dc - std::panicking::try::do_call::h7caaaeaf9401650b
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  28:     0x5579757238dc - std::panicking::try::he7d15285746cbbc2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  29:     0x5579757238dc - std::panic::catch_unwind::h89fb4f50c0301fe0
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  30:     0x5579757238dc - std::rt::lang_start_internal::h078acd489417d3c1
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
  31:     0x557973868fc5 - main
  32:     0x7f241d77d083 - __libc_start_main
  33:     0x55797374d40a - _start
  34:                0x0 - <unknown>
```

**Comment by ko0hi** [comment]
Adding a line `ulimit -n 1000000` in the validator script solved the problem, and finally I was able to get a response via localhost.

The modified version is here:

```bash
#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail
# Remove empty snapshots
find "/var/solana/data/ledger" -name "snapshot-*" -size 0 -print -exec rm {} \; || true
export RUST_LOG=warning
export RUST_BACKTRACE=full
export SOLANA_METRICS_CONFIG=__SOLANA_METRICS_CONFIG__

cd /home/solana
ln -s /var/solana/data/ledger .
ulimit -n 1000000

/home/solana/bin/solana-validator \
--ledger /var/solana/data/ledger \
--identity /home/solana/config/validator-keypair.json \
__KNOWN_VALIDATORS__ \
--expected-genesis-hash __EXPECTED_GENESIS_HASH__ \
__ENTRY_POINTS__ \
--no-voting \
--snapshot-interval-slots 500 \
--maximum-local-snapshot-age 500 \
--full-rpc-api \
--rpc-port 8899 \
--gossip-port 8801 \
--dynamic-port-range 8800-8813 \
--no-port-check \
--wal-recovery-mode skip_any_corrupted_record \
--enable-rpc-transaction-history \
--enable-cpi-and-log-storage \
--init-complete-file /var/solana/data/init-completed \
--snapshot-compression none \
--require-tower \
--no-wait-for-vote-to-start-leader \
--limit-ledger-size 50000000 \
--accounts /var/solana/accounts \
--no-os-cpu-stats-reporting \
--no-os-memory-stats-reporting \
--no-os-network-stats-reporting \
--log -
```

**Comment by frbrkoala** [comment]
Thank you for this detailed bug report and solution!
I have not seen such error before, but I'll test out the changes to the script and will make the change.

**Comment by charaZyworld** [comment]
"Client error: test-ledger/admin.rpc does not exist,"  is the error i got when trying to run my test validator. Solved it by accident figure maybe this will help someone else. On windows WSL have to log into your distro with the sudo password. My case i tried to run sudo solana-test-validator. That gave me an error after i entered my PW but then trying just solana-test-validator immediately after it started right up. Assuming its cause by firewall protections.
